### ISSUE TITLE
[Question] The format of the TCP/IP packet

### ISSUE THREAD

**Issue by u93132** [xzn/ntrviewer-hr#2]
I am trying to apply the new ip port feature and reading your TCP/IP packet, and this is what I get. Can you tell me what are the four bytes for?

The port assign feature is nice and allows one PC to connect with several 3DS.

![packet](https://github.com/xzn/ntrviewer-hr/assets/87488149/be7ef63b-b6c2-40e8-b0f0-d3176800b9a5)

**Comment by xzn** [comment]
It just a random number. If that number is set then the next two bytes are the port number otherwise ignore the next two bytes.

Existing viewers all use zero at those bytes so this is probably redundant, I just wanted to use a magic number just in case.

(Basically, if you want to set port number, those four bytes need to be those exact bytes, it functions similarly to the 12345678 earlier)

**Comment by u93132** [comment]
Nice, thank you!
