### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by korbosoft** [xzn/ntrviewer-hr#3]
Is it possible?

**Comment by xzn** [comment]
Should be. It works in wine in the meantime though if you don't mind.

Edit:

Seems to not work with Nvidia's driver (complains about uninitialized variables and the interface is missing). Only work with Mesa for now. Maybe I'll do a Linux build after all.

**Comment by xzn** [comment]
Requires SDL2, libturbojpeg and NCNN (I'll figure out how to make this an optional dependency in the future, for now it's needed to launch I think)

~[ntrviewer.zip](https://github.com/xzn/ntrviewer-hr/files/14289195/ntrviewer.zip)~

If you don't mind giving this a test and let me know how it works on your end, that'd be great.

~Currently it has some hi-dpi issues but otherwise it seems to work.~ Seems fixed with `SDL_VIDEODRIVER=wayland`

~P.S.: I couldn't get SIMD from libjpeg-turbo to work, it just crashes. Worked on Windows though so IDK what's going on? (Unless it actually wasn't working on Windows either..)~ I forgot that compilation flags for assembly is different on Linux..


~Update:~

~[ntrviewer.zip](https://github.com/xzn/ntrviewer-hr/files/14289545/ntrviewer.zip)~

Update 2 (working hi-dpi this time, hopefully no other issues):

[ntrviewer.zip](https://github.com/xzn/ntrviewer-hr/files/14300543/ntrviewer.zip)

**Comment by korbosoft** [comment]
Everything seems to work fine.

**Comment by xzn** [comment]
I've added Linux build here:

~https://github.com/xzn/ntrviewer-hr/releases/tag/v0.1.4.1~

Almost everything is statically linked so only glibc is needed to run.

Edit:

Fixed OpenGL shader usage for MESA

https://github.com/xzn/ntrviewer-hr/releases/tag/v0.1.4.2
